version: '3'

services:

  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_USER=user
      - INFLUX_USER_PASSWORD=3Dprinter
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=3Dprinter
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:10.1.2
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=3Dprinter
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
     - influxdb
    links:
     - influxdb

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    restart: always
    ports:
      - "1880:1880"
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - node-red-data:/data
    depends_on:
      - influxdb
      - mosquitto
    links:
      - influxdb
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log

#  portainer:
#    image: portainer/portainer-ce:latest
#    container_name: portainer
#    restart: always
#    ports:
#      - 9443:9443
#    volumes:
#        - portainer_data:/data
#        - /var/run/docker.sock:/var/run/docker.sock
  
volumes:
  influxdb_data: {}
  grafana_data: {}
  node-red-data: {}
#  portainer_data: {}